<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\ServiceCategory;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get category ID mapping
        $categories = ServiceCategory::pluck('id', 'name');

        $services = [
            // ==================== KEPEGAWAIAN ====================
            [
                'name' => 'Surat Pernyataan Tidak Pernah Dikenakan Hukuman Disiplin Sedang/Berat',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan penerbitan surat pernyataan tidak pernah dikenakan hukuman disiplin sedang atau berat untuk keperluan administrasi kepegawaian.',
                'requirements' => "- Fotokopi SK terakhir\n- Surat pengantar dari kepala sekolah/ satuan kerja\n- Kartu Pegawai (KARPEG)\n-Fotokopi KTP",
                'workflow' => "1. Pemohon mengajukan surat pengantar dari satuan kerja\n2. Petugas memproses verifikasi data\n3. Kepala Kantor menandatangani surat\n4. Surat siap diambil",
                'processing_time' => '3-5 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Tanda Kehormatan Satyalancana Karya Satya',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan pengajuan tanda kehormatan Satyalancana Karya Satya untuk PNS yang telah mengabdi 10, 20, atau 30 tahun.',
                'requirements' => "- Fotokopi SK pengangkatan pertama\n- Fotokopi SK terakhir\n- Daftar hadir 10 tahun terakhir\n- Pas foto 3x4 (2 lembar)\n- Fotokopi KARPEG",
                'workflow' => "1. Pemohon melengkapi berkas\n2. Verifikasi masa kerja\n3. Pengajuan ke Kanwil Kemenang\n4. Proses di tingkat provinsi\n5. Penyerahan tanda kehormatan",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Surat Pengantar Usul Ijin Belajar',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan penerbitan surat pengantar untuk mengajukan ijin belajar bagi PNS yang ingin melanjutkan pendidikan.',
                'requirements' => "- Surat permohonan dari PNS\n- Fotokopi SK pengangkatan\n- Surat rekomendasi dari kepala sekolah\n- Kartu Pegawai\n- Proposed study/rencana pendidikan",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan surat pengantar\n4. Penyerahan ke pemohon",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Surat Izin Cuti',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan pengajuan dan penerbitan surat izin cuti bagi PNS.',
                'requirements' => "- Surat permohonan cuti\n- SK cuti tahun sebelumnya (bagi cuti tahunan)\n- Daftar hadir\n- Approved dari atasan\n- Fotokopi KTP",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi hak cuti\n3. Persetujuan atasan\n4. Penerbitan SK cuti\n5. Penyerahan ke pemohon",
                'processing_time' => '3-5 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Kenaikan Pangkat',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan pengajuan kenaikan pangkat regular bagi PNS yang memenuhi persyaratan.',
                'requirements' => "- SK pangkat terakhir\n- SKP 2 tahun terakhir\n- PAK (Penetapan Angka Kredit) bagi fungsional\n- Pas foto 3x4 (2 lembar)\n- Daftar hadir\n- Fotokopi KARPEG",
                'workflow' => "1. Pemohon melengkapi berkas\n2. Verifikasi kelengkapan oleh kasubag\n3. Proses di bidang kepegawaian\n4. Pengajuan ke Kanwil\n5. Penetapan kenaikan pangkat",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Pencantuman Gelar Pendidikan Pegawai',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan pengajuan pencantuman gelar pendidikan pada dokumen kepegawaian.',
                'requirements' => "- Fotokopi ijazah yang telah dilegalisir\n- Transkrip nilai\n- SK pengangkatan\n- Surat pernyataan kebenaran dokumen\n- Pas foto 3x4",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi ijazah\n3. Proses administrasi\n4. Penetapan pencantuman gelar\n5. Pemberitahuan ke pemohon",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Pensiun',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan pengajuan pensiun PNS karena mencapai batas usia pensiun atau atas permintaan sendiri.',
                'requirements' => "- SK terakhir\n- Fotokopi KTP\n- Fotokopi KK\n- Akta nikah (bagi yang sudah menikah)\n- SK pangkat terakhir\n- Daftar gaji terakhir",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kelengkapan berkas\n3. Proses di bidang kepegawaian\n4. Pengajuan ke Kanwil untuk persetujuan\n5. Penerbitan SK pensiun",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Pensiun Dini',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan pengajuan pensiun dini bagi PNS yang memenuhi persyaratan.',
                'requirements' => "- SK terakhir\n- Fotokopi KTP\n- Surat alasan pensiun dini\n- Persetujuan keluarga (bagi yang sudah menikah)\n- SK pangkat terakhir",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Proses di bidang kepegawaian\n4. Pengajuan ke Kanwil\n5. Penetapan pensiun dini",
                'processing_time' => '30-90 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Surat Pengantar Ijin Tugas Belajar',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan penerbitan surat pengantar untuk ijin tugas belajar bagi PNS.',
                'requirements' => "- Surat permohonan dari PNS\n- Fotokopi SK pengangkatan\n- Fotokopi ijazah terakhir\n- Rekomendasi dari kepala sekolah\n- Proposed study",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan surat pengantar\n4. Penyerahan ke pemohon",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Mutasi Pegawai PNS',
                'service_category_id' => $categories['Kepegawaian'],
                'description' => 'Layanan pengajuan mutasi/antarkan pegawai PNS antar satuan kerja.',
                'requirements' => "- Surat permohonan mutasi\n- SK terakhir\n- Persetujuan dari satuan kerja asal dan tujuan\n- Alasan mutasi\n- Fotokopi KTP",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kelengkapan\n3. Proses di bidang kepegawaian\n4. Pengajuan ke Kanwil\n5. Penetapan mutasi",
                'processing_time' => '30-90 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== UMUM & FKUB ====================
            [
                'name' => 'Permohonan Rohaniawan Pembaca Doa',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan permohonan rohaniawan untuk pembaca doa dalam acara resmi.',
                'requirements' => "- Surat permohonan resmi\n- Detail acara\n- Tanggal dan waktu acara\n- Tempat acara\n- Jumlah peserta",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kebutuhan\n3. Penunjukan rohaniawan\n4. Konfirmasi ke pemohon",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Persetujuan Penelitian',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan penerbitan rekomendasi untuk penelitian di lingkungan Kementerian Agama Kabupaten Nganjuk.',
                'requirements' => "- Surat pengantar dari lembaga/institusi\n- Proposal penelitian\n- Fotokopi KTP pemohon\n- Jadwal penelitian\n- Surat ethical clearance (jika diperlukan)",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi proposal\n3. Review kelayakan\n4. Penerbitan rekomendasi\n5. Penyerahan ke pemohon",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Studi Banding/Studi Lapangan/Kunjungan Kerja',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan permohonan untuk melakukan studi banding atau kunjungan kerja.',
                'requirements' => "- Surat permohonan resmi\n- Proposal/struktur kunjungan\n- Jumlah peserta\n- Tanggal dan durasi\n- Tujuan kunjungan",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kelengkapan\n3. Penjadwalan\n4. Konfirmasi ke pemohon\n5. Pelaksanaan kunjungan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis (transportasi ditanggung pemohon)',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Magang/PPL/PKL',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan permohonan magang, PPL, atau PKL untuk mahasiswa dari berbagai jenjang pendidikan.',
                'requirements' => "- Surat pengantar dari kampus/sekolah\n- Proposal magang\n- Daftar nama peserta\n- Fotokopi KTP setiap peserta\n- Jadwal magang",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kelengkapan\n3. Penempatan di unit kerja\n4. Penyerahan Surat Tugas\n5. Pelaksanaan magang",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Kegiatan',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan penerbitan rekomendasi untuk kegiatan keagamaan atau pendidikan.',
                'requirements' => "- Surat permohonan\n- Proposal kegiatan\n- Susunan panitia\n- Jadwal kegiatan\n- Surat dukungan dari desa/kelurahan",
                'workflow' => "1. Pengajuan surat permohonan\n2. Review proposal\n3. Verifikasi kelengkapan\n4. Penerbitan rekomendasi\n5. Penyerahan",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Audiensi',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan permohonan audiensi dengan pejabat Kantor Kementerian Agama.',
                'requirements' => "- Surat permohonan audiensi\n- Agenda/tema audiensi\n- Jumlah peserta\n- Identitas penanggung jawab\n- Waktu yang diinginkan",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kebutuhan\n3. Penjadwalan audiensi\n4. Konfirmasi ke pemohon\n5. Pelaksanaan audiensi",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan MOU',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan permohonan kerja sama melalui Memorandum of Understanding.',
                'requirements' => "- Surat permohonan kerja sama\n- Draft MOU\n- Profil institusi\n- Legalitas lembaga\n- Tujuan kerja sama",
                'workflow' => "1. Pengajuan permohonan\n2. Review draft MOU\n3. Negosiasi (jika perlu)\n4. Penetapan MOU\n5. Penandatanganan",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Narasumber Kegiatan',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan permohonan narasumber untuk kegiatan pelatihan atau seminar.',
                'requirements' => "- Surat permohonan\n- Proposal kegiatan\n- Tema yang dibahas\n- Jadwal kegiatan\n- Target peserta",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kebutuhan\n3. Penunjukan narasumber\n4. Konfirmasi ke pemohon\n5. Pelaksanaan kegiatan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis (honor sesuai ketentuan)',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Penawaran/Promosi',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan untuk mengajukan penawaran atau promosi kegiatan/informasi.',
                'requirements' => "- Surat penawaran resmi\n- Materi/informasi yang dipromosikan\n- Target audiensi\n- Jadwal promosi\n- Legalitas lembaga",
                'workflow' => "1. Pengajuan surat penawaran\n2. Review materi\n3. Verifikasi kelayakan\n4. Persetujuan\n5. Konfirmasi ke pemohon",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Data Informasi',
                'service_category_id' => $categories['Umum & FKUB'],
                'description' => 'Layanan permohonan data atau informasi dari Kantor Kemenag.',
                'requirements' => "- Surat permohonan resmi\n- Identitas pemohon\n- Jenis data yang diperlukan\n- Tujuan penggunaan data\n- Tanda tangan pemohon",
                'workflow' => "1. Pengajuan surat permohonan\n2. Verifikasi kelengkapan\n3. Pencarian data\n4. Persetujuan atasan\n5. Penyerahan data",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== PENDIDIKAN MADRASAH ====================
            [
                'name' => 'Rekomendasi Melanjutkan Sekolah/Kuliah ke Luar Negeri',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi untuk melanjutkan pendidikan ke luar negeri.',
                'requirements' => "- Surat permohonan\n- Fotokopi rapor/ijazah\n- Paspor\n- Surat diterima dari sekolah luar negeri\n- Pas foto",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Bantuan Sarana/Prasarana',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan pengajuan rekomendasi untuk bantuan sarana dan prasarana pendidikan.',
                'requirements' => "- Surat permohonan\n- Proposal bantuan\n- Data sekolah\n- Kebutuhan sarana/prasarana\n- RAB",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelayakan\n3. Survey lapangan\n4. Penerbitan rekomendasi\n5. Proses lebih lanjut di tingkat provinsi",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Kepala Madrasah Baru',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan pengajuan dan penetapan kepala madrasah baru.',
                'requirements' => "- Surat pengantar kepala sekolah lama\n- SK pengangkatan terakhir\n- Fotokopi ijazah\n- SK tugas mengajar\n- Daftar hadir",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Proses di bidang pendidikan\n4. Penetapan\n5. Penerbitan SK",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Mutasi Siswa Dalam Provinsi',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi mutasi siswa dalam provinsi Jawa Timur.',
                'requirements' => "- Surat permohonan orang tua\n- SKHU/Surat keterangan lulus\n- Pas foto\n- Fotokopi KTP orang tua\n- Surat keterangan layak pindahan",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Penelitian di Madrasah',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi untuk melakukan penelitian di madrasah.',
                'requirements' => "- Surat pengantar lembaga\n- Proposal penelitian\n- Fotokopi KTP peneliti\n- Jadwal penelitian\n- Ethical clearance (jika perlu)",
                'workflow' => "1. Pengajuan permohonan\n2. Review proposal\n3. Verifikasi kelengkapan\n4. Penerbitan rekomendasi\n5. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Lomba di Madrasah',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi untuk mengikuti lomba di tingkat yang lebih tinggi.',
                'requirements' => "- Surat permohonan sekolah\n- Pengumuman lomba\n- Daftar peserta\n- Fasilitas pendukung\n- Jadwal lomba",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelayakan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Akreditasi',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi akreditasi madrasah.',
                'requirements' => "- Surat permohonan\n- Data madrasah\n- Portofolio sekolah\n- SK operasional\n- Dokumen pendukung",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Proses BAN-PM\n4. Penetapan hasil\n5. Penerbitan sertifikat",
                'processing_time' => '30-90 hari kerja',
                'cost' => 'Gratis (biaya akreditasi ke BAN-PM)',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Surat Pengantar Kurikulum MA',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan surat pengantar terkait kurikulum Madrasah Aliyah.',
                'requirements' => "- Surat permohonan sekolah\n- Detail kebutuhan kurikulum\n- Kelas yang terlibat\n- Jadwal implementasi",
                'workflow' => "1. Pengajuan surat\n2. Verifikasi\n3. Penerbitan surat\n4. Penyerahan",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi PPDB',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi PPDB untuk penerimaan peserta didik baru.',
                'requirements' => "- Surat permohonan\n- Ketentuan PPDB\n- Data calon peserta\n- Berkas pendukung",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengesahan RKTM dan RKJM',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan pengesahan Rencana Kerja Tahunan Madrasah dan Rencana Kerja Madrasah.',
                'requirements' => "- Draft RKTM/RKJM\n- Data madrasah\n- Program kerja\n- Pertimbangan dewan guru",
                'workflow' => "1. Pengajuan draft\n2. Review\n3. Revisi (jika perlu)\n4. Pengesahan\n5. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi IKM',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi Implementasi Kurikulum Merdeka.',
                'requirements' => "- Surat permohonan\n- Profil madrasah\n- Rencana implementasi\n- Daftar guru",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelayakan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Mutasi Siswa ke Luar Provinsi',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi mutasi siswa ke luar provinsi.',
                'requirements' => "- Surat permohonan orang tua\n- SKHU\n- Pas foto\n- Fotokopi KTP orang tua\n- Surat keterangan layak pindahan",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengesahan Kurikulum',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan pengesahan kurikulum yang digunakan madrasah.',
                'requirements' => "- Draft kurikulum\n- Silabus\n- RPP\n- SK operasional madrasah",
                'workflow' => "1. Pengajuan draft\n2. Review kurikulum\n3. Revisi (jika perlu)\n4. Pengesahan\n5. Penyerahan",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Paspor Belajar',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan rekomendasi untuk pengurusan paspor belajar ke luar negeri.',
                'requirements' => "- Surat permohonan\n- Fotokopi ijazah\n- Surat diterima dari luar negeri\n- Pas foto\n- Fotokopi KTP",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Kegiatan Pendidikan',
                'service_category_id' => $categories['Pendidikan Madrasah'],
                'description' => 'Layanan penerbitan rekomendasi untuk kegiatan pendidikan seperti diklat, seminar, workshop.',
                'requirements' => "- Surat permohonan\n- Proposal kegiatan\n- Jadwal\n- Target peserta\n- Narasumber",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelayakan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== PENDIDIKAN DINIYAH & PONDOK PESANTREN ====================
            [
                'name' => 'Rekomendasi Izin Tinggal/Belajar Terbatas (ITAS) Asing',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi untuk izin tinggal/belajar terbatas bagi warga asing.',
                'requirements' => "- Surat permohonan\n- Paspor\n- Fotokopi KTP sponsor\n- Surat keterangan belajar\n- Pas foto",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Proses di Imigrasi",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Izin Operasional Madrasah Diniyah Takmiliyah Ulya',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi izin operasional untuk Madrasah Diniyah tingkat Ulya.',
                'requirements' => "- Surat permohonan\n- Akta yayasan\n- SK operasional\n- Daftar guru\n- Kurikulum",
                'workflow' => "1. Pengajuan permohonan\n2. Survey lapangan\n3. Verifikasi kelayakan\n4. Penerbitan rekomendasi\n5. Proses di Kanwil",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Izin Operasional Pendidikan Diniyah Formal',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi izin operasional pendidikan diniyah formal.',
                'requirements' => "- Surat permohonan\n- Akta yayasan\n- SK operasional\n- Data pengajar\n- Kurikulum",
                'workflow' => "1. Pengajuan permohonan\n2. Survey\n3. Verifikasi\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Bantuan Pondok Pesantren',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi untuk bantuan ke lembaga pondok pesantren.',
                'requirements' => "- Surat permohonan\n- Proposal bantuan\n- Data pesantren\n- Legalitas yayasan\n- RAB",
                'workflow' => "1. Pengajuan permohonan\n2. Survey lapangan\n3. Verifikasi kelayakan\n4. Penerbitan rekomendasi\n5. Proses di tingkat pusat",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Izin Penelitian Pondok Pesantren',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi untuk melakukan penelitian di pondok pesantren.',
                'requirements' => "- Surat pengantar\n- Proposal penelitian\n- Fotokopi KTP\n- Jadwal penelitian",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Izin Operasional Pendidikan Kesetaraan Pondok Pesantren',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi izin operasional pendidikan kesetaraan pada Pondok Pesantren Salafiyah.',
                'requirements' => "- Surat permohonan\n- Akta yayasan\n- SK operasional pesantren\n- Data peserta\n- Kurikulum",
                'workflow' => "1. Pengajuan permohonan\n2. Survey\n3. Verifikasi\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => "Rekomendasi Izin Operasional Ma'had Aly",
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => "Layanan rekomendasi izin operasional Ma'had Aly.",
                'requirements' => "- Surat permohonan\n- Akta pondok\n- Data pengajar\n- Kurikulum\n- Fasilitas",
                'workflow' => "1. Pengajuan permohonan\n2. Survey lapangan\n3. Verifikasi kelayakan\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil/Pusat",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Izin Operasional Satuan Pendidikan Muadalah',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi izin operasional satuan pendidikan muadalah.',
                'requirements' => "- Surat permohonan\n- Akta yayasan\n- SK operasional\n- Kurikulum\n- Data guru",
                'workflow' => "1. Pengajuan permohonan\n2. Survey\n3. Verifikasi\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Melanjutkan Studi ke Luar Negeri',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan rekomendasi untuk santri yang ingin melanjutkan studi ke luar negeri.',
                'requirements' => "- Surat permohonan\n- Surat keterangan pesantren\n- Fotokopi ijazah\n- Pas foto\n- Surat diterima dari luar negeri",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Rekomendasi Paspor Belajar Santri',
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => 'Layanan pengajuan rekomendasi paspor belajar untuk santri.',
                'requirements' => "- Surat permohonan\n- Surat keterangan pesantren\n- Fotokopi ijazah\n- Pas foto\n- Fotokopi KTP",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => "Permohonan Rekomendasi Tahfidz Al-Qur'an",
                'service_category_id' => $categories['Pendidikan Diniyah dan Pondok Pesantren'],
                'description' => "Layanan penerbitan rekomendasi program tahfidz Al-Qur'an.",
                'requirements' => "- Surat permohonan\n- Data lembaga\n- Program tahfidz\n- Jumlah penghafal\n- Sertifikat (jika ada)",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelayakan\n3. Penerbitan rekomendasi\n4. Penyerahan",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== PENDIDIKAN AGAMA ISLAM ====================
            [
                'name' => 'Dispensasi Kelayakan Tunjangan PAI',
                'service_category_id' => $categories['Pendidikan Agama Islam'],
                'description' => 'Layanan dispensasi kelayakan untuk pengajuan tunjangan khusus guru PAI.',
                'requirements' => "- SK pengangkatan\n- Fotokopi ijazah\n- Sertifikat pendidik\n- Daftar hadir\n- Data sekolah",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Proses kelayakan\n4. Penerbitan dispensasi",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pembuatan Akun SIAGA',
                'service_category_id' => $categories['Pendidikan Agama Islam'],
                'description' => 'Layanan pembuatan dan aktivasi akun SIAGA untuk guru PAI.',
                'requirements' => "- Fotokopi SK\n- Fotokopi ijazah\n- Pas foto\n- Data sekolah\n- NUPTK (jika ada)",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi data\n3. Pembuatan akun\n4. Konfirmasi ke pemohon",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pengajuan Akun Emis',
                'service_category_id' => $categories['Pendidikan Agama Islam'],
                'description' => 'Layanan pengajuan akun EMIS untuk lembaga pendidikan agama.',
                'requirements' => "- Surat permohonan\n- Data lembaga\n- SK operasional\n- Fotokopi KTP penanggung jawab",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi data\n3. Pembuatan akun\n4. Konfirmasi",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Pendataan Sertifikasi Guru PAI',
                'service_category_id' => $categories['Pendidikan Agama Islam'],
                'description' => 'Layanan pendataan dan verifikasi sertifikasi guru PAI.',
                'requirements' => "- Fotokopi Sertifikat Pendidik\n- Fotokopi ijazah\n- SK pengangkatan\n- Data diri guru",
                'workflow' => "1. Pengajuan pendataan\n2. Verifikasi dokumen\n3. Entry data\n4. Konfirmasi",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Penerbitan NUPTK',
                'service_category_id' => $categories['Pendidikan Agama Islam'],
                'description' => 'Layanan permohonan penerbitan Nomor Unik Pendidik dan Tenaga Kependidikan.',
                'requirements' => "- Fotokopi SK\n- Fotokopi ijazah\n- Pas foto\n- Data diri lengkap\n- Surat keterangan sekolah",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi data\n3. Proses ke Pusat\n4. Penerbitan NUPTK",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Perubahan Data Personal SIAGA',
                'service_category_id' => $categories['Pendidikan Agama Islam'],
                'description' => 'Layanan permohonan perubahan data personal di akun SIAGA.',
                'requirements' => "- Surat permohonan\n- Data lama\n- Data baru\n- Dokumen pendukung\n- Fotokopi KTP",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi perubahan\n3. Update data\n4. Konfirmasi",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== BIMBINGAN MASYARAKAT ISLAM ====================
            [
                'name' => "Permohonan Surat Keterangan Majelis Ta'lim Terdaftar",
                'service_category_id' => $categories['Bimbingan Masyarakat Islam'],
                'description' => "Layanan penerbitan surat keterangan pendaftaran majelis ta'lim.",
                'requirements' => "- Surat permohonan\n- Data majelis ta'lim\n- Susunan kepengurusan\n- Jadwal kegiatan\n- Daftar hadir anggota",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi data\n3. Survey (jika perlu)\n4. Penerbitan surat\n5. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Piagam Masjid',
                'service_category_id' => $categories['Bimbingan Masyarakat Islam'],
                'description' => 'Layanan penerbitan piagam pengukuhan/pengelolaan masjid.',
                'requirements' => "- Surat permohonan\n- Data masjid\n- Luas tanah\n- Denah lokasi\n- SKT dari desa",
                'workflow' => "1. Pengajuan permohonan\n2. Survey lokasi\n3. Verifikasi kelayakan\n4. Penerbitan piagam\n5. Penyerahan",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Piagam Mushola',
                'service_category_id' => $categories['Bimbingan Masyarakat Islam'],
                'description' => 'Layanan penerbitan piagam pengukuhan/pengelolaan mushola.',
                'requirements' => "- Surat permohonan\n- Data mushola\n- Luas tanah\n- Denah lokasi\n- SKT dari desa",
                'workflow' => "1. Pengajuan permohonan\n2. Survey lokasi\n3. Verifikasi kelayakan\n4. Penerbitan piagam\n5. Penyerahan",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Penelitian di KUA',
                'service_category_id' => $categories['Bimbingan Masyarakat Islam'],
                'description' => 'Layanan rekomendasi untuk penelitian di KUA Kecamatan.',
                'requirements' => "- Surat pengantar\n- Proposal penelitian\n- Fotokopi KTP\n- Jadwal penelitian",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Koordinasi dengan KUA\n4. Penerbitan rekomendasi\n5. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Sertifikat Arah Kiblat',
                'service_category_id' => $categories['Bimbingan Masyarakat Islam'],
                'description' => 'Layanan penerbitan sertifikat arah kiblat untuk masjid/mushola.',
                'requirements' => "- Surat permohonan\n- Data masjid/mushola\n- Koordinat lokasi\n- Foto bangunan",
                'workflow' => "1. Pengajuan permohonan\n2. Survey kiblat\n3. Pengukuran arah\n4. Penerbitan sertifikat\n5. Penyerahan",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Bantuan Masjid/Musholla',
                'service_category_id' => $categories['Bimbingan Masyarakat Islam'],
                'description' => 'Layanan rekomendasi untuk pengajuan bantuan masjid/musholla.',
                'requirements' => "- Surat permohonan\n- Data masjid/musholla\n- Proposal bantuan\n- RAB\n- Foto kondisi",
                'workflow' => "1. Pengajuan permohonan\n2. Survey lapangan\n3. Verifikasi kelayakan\n4. Penerbitan rekomendasi\n5. Proses ke tingkat pusat",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== ZAKAT DAN WAKAF ====================
            [
                'name' => 'Sertifikasi Tanah Wakaf',
                'service_category_id' => $categories['Zakat dan Wakaf'],
                'description' => 'Layanan bantuan pengurusan sertifikasi tanah wakaf.',
                'requirements' => "- Surat permohonan\n- Akta ikrar wakaf\n- Sertifikat tanah asli\n- KTP wakif\n- KTP nazir\n- Peta lokasi",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi dokumen\n3. Pendampingan ke BPN\n4. Proses sertifikasi\n5. Penyerahan sertifikat",
                'processing_time' => '30-90 hari kerja',
                'cost' => 'Gratis (biaya BPN ditanggung pemohon)',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Pembentukan Lembaga Amil Zakat',
                'service_category_id' => $categories['Zakat dan Wakaf'],
                'description' => 'Layanan rekomendasi pembentukan Lembaga Amil Zakat (LAZ).',
                'requirements' => "- Surat permohonan\n- Akta notaris\n- AD/ART\n- Struktur organisasi\n- Proposal program",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Survey\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil/Pusat",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Pergantian Nadzir Perseorangan',
                'service_category_id' => $categories['Zakat dan Wakaf'],
                'description' => 'Layanan rekomendasi pergantian nadzir wakaf perseorangan.',
                'requirements' => "- Surat permohonan\n- SK nadzir lama\n- KTP nadzir baru\n- Akta ikrar wakaf\n- Surat persetujuan wakif",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Survey\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Perubahan Nadzir Perseorangan',
                'service_category_id' => $categories['Zakat dan Wakaf'],
                'description' => 'Layanan perubahan nadzir untuk wakaf perseorangan.',
                'requirements' => "- Surat permohonan\n- Data nadzir lama dan baru\n- Akta ikrar\n- KTP\n- Surat persetujuan wakif",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi data\n3. Penerbitan SK perubahan\n4. Penyerahan",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Pergantian Nadzir Organisasi',
                'service_category_id' => $categories['Zakat dan Wakaf'],
                'description' => 'Layanan rekomendasi pergantian nadzir organisasi/badan hukum.',
                'requirements' => "- Surat permohonan\n- SK nadzir lama\n- Akta pendirian\n- KTP penanggung jawab baru\n- Akta ikrar wakaf",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Survey\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Izin Tukar Menukar Harta Benda Wakaf',
                'service_category_id' => $categories['Zakat dan Wakaf'],
                'description' => 'Layanan rekomendasi tukar menukar harta benda wakaf.',
                'requirements' => "- Surat permohonan\n- Akta ikrar wakaf\n- Sertifikat tanah\n- Proposal tukar menukar\n- Persetujuan nazir",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Survey lokasi\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Rekomendasi Perubahan Peruntukan Wakaf',
                'service_category_id' => $categories['Zakat dan Wakaf'],
                'description' => 'Layanan rekomendasi perubahan peruntukan tanah wakaf.',
                'requirements' => "- Surat permohonan\n- Akta ikrar wakaf\n- Sertifikat tanah\n- Alasan perubahan\n- Persetujuan wakif dan nazir",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Survey\n4. Penerbitan rekomendasi\n5. Proses ke Kanwil",
                'processing_time' => '30-60 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== KEARSIPAN ====================
            [
                'name' => 'Permohonan Pengelolaan Arsip Dinamis',
                'service_category_id' => $categories['Kearsipan'],
                'description' => 'Layanan permohonan pengelolaan arsip dinamis (penciptaan, penggunaan, pemeliharaan, dan disposition).',
                'requirements' => "- Surat permohonan\n- Daftar arsip\n- Klasifikasi keamanan\n- Jadwal retensi",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Review klasifikasi\n4. Penerbitan persetujuan\n5. Penyerahan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Pengelolaan Arsip Statis',
                'service_category_id' => $categories['Kearsipan'],
                'description' => 'Layanan permohonan pengelolaan arsip statis (penyerahan, pemindahan, dan pemanfaatan).',
                'requirements' => "- Surat permohonan\n- Daftar arsip yang diajukan\n- Berita acara serah terima\n- Deskripsi arsip",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Seleksi arsip\n4. Penyerahan ke balai arsip\n5. Penerbitan berita acara",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Pembinaan Kearsipan',
                'service_category_id' => $categories['Kearsipan'],
                'description' => 'Layanan permohonan pembinaan kearsipan untuk satuan kerja.',
                'requirements' => "- Surat permohonan\n- Data satuan kerja\n- Permasalahan kearsipan\n- Jadwal yang diinginkan",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kebutuhan\n3. Penjadwalan\n4. Pelaksanaan Pembinaan\n5. Evaluasi",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Pengolahan Arsip menjadi Informasi',
                'service_category_id' => $categories['Kearsipan'],
                'description' => 'Layanan permohonan pengolahan dan penyajian arsip menjadi informasi.',
                'requirements' => "- Surat permohonan\n- Daftar arsip yang diperlukan\n- Formulir permintaan informasi\n- Tujuan penggunaan",
                'workflow' => "1. Pengajuan permohonan\n2. Identifikasi arsip\n3. Pengolahan data\n4. Penyajian informasi\n5. Penyerahan informasi",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== PEMBINAAN AGAMA KRISTEN ====================
            [
                'name' => 'Permohonan Data Umat Kristen',
                'service_category_id' => $categories['Pembinaan Agama Kristen'],
                'description' => 'Layanan permohonan data umat beragama Kristen di wilayah Nganjuk.',
                'requirements' => "- Surat permohonan resmi\n- Identitas pemohon\n- Tujuan penggunaan data\n- Komitmen kerahasiaan data",
                'workflow' => "1. Pengajuan surat\n2. Verifikasi kelengkapan\n3. Proses pencarian data\n4. Persetujuan atasan\n5. Penyerahan data",
                'processing_time' => '5-10 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Penyuluhan Online Umat Kristen',
                'service_category_id' => $categories['Pembinaan Agama Kristen'],
                'description' => 'Layanan permohonan penyuluhan keagamaan secara online.',
                'requirements' => "- Surat permohonan\n- Tema penyuluhan\n- Target peserta\n- Jadwal yang diinginkan\n- Platform yang digunakan",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelayakan\n3. Penjadwalan\n4. Pelaksanaan\n5. Laporan",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Konseling Penyuluh Agama Kristen',
                'service_category_id' => $categories['Pembinaan Agama Kristen'],
                'description' => 'Layanan permohonan konseling oleh penyuluh agama Kristen.',
                'requirements' => "- Surat permohonan\n- Identitas pemohon\n- Topik/isu yang dikonselingkan\n- Jadwal yang diinginkan",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kebutuhan\n3. Penjadwalan konseling\n4. Pelaksanaan\n5. Tindak lanjut",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Pendampingan Mediasi',
                'service_category_id' => $categories['Pembinaan Agama Kristen'],
                'description' => 'Layanan permohonan pendampingan mediasi oleh penyuluh agama Kristen.',
                'requirements' => "- Surat permohonan\n- Kronologi permasalahan\n- Data pihak terkait\n- Usulan solusi",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi permasalahan\n3. Penjadwalan mediasi\n4. Pelaksanaan\n5. Kesepakatan bersama",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Bimbingan Penyuluhan Agama Kristen',
                'service_category_id' => $categories['Pembinaan Agama Kristen'],
                'description' => 'Layanan permohonan bimbingan dan penyuluhan agama Kristen.',
                'requirements' => "- Surat permohonan\n- Topik bimbingan\n- Target kelompok\n- Jadwal yang diinginkan",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kebutuhan\n3. Penjadwalan\n4. Pelaksanaan\n5. Evaluasi",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Pembinaan Umat Kristen',
                'service_category_id' => $categories['Pembinaan Agama Kristen'],
                'description' => 'Layanan permohonan pembinaan umat beragama Kristen.',
                'requirements' => "- Surat permohonan\n- Jenis kegiatan\n- Target peserta\n- Jadwal\n- Fasilitas yang diperlukan",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelayakan\n3. Penjadwalan\n4. Pelaksanaan\n5. Laporan hasil",
                'processing_time' => '7-14 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],

            // ==================== KEHUMASAN ====================
            [
                'name' => 'Permohonan Informasi',
                'service_category_id' => $categories['Kehumasan'],
                'description' => 'Layanan permohonan informasi publik sesuai UU KIP.',
                'requirements' => "- Surat permohonan informasi\n- Identitas pemohon\n- Rincian informasi yang dimohon\n- Tujuan penggunaan informasi",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kelengkapan\n3. Pencarian informasi\n4. Persetujuan PPID\n5. Penyerahan informasi",
                'processing_time' => '3-10 hari kerja',
                'cost' => 'Gratis (biaya penggandaan ditanggung pemohon)',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Permohonan Media Relation',
                'service_category_id' => $categories['Kehumasan'],
                'description' => 'Layanan permohonan liputan dan hubungan dengan media.',
                'requirements' => "- Surat permohonan liputan\n- Topic/kegiatan\n- Jadwal\n- Data kontak media",
                'workflow' => "1. Pengajuan permohonan\n2. Verifikasi kegiatan\n3. Penjadwalan liputan\n4. Koordinasi dengan media\n5. Pelaksanaan",
                'processing_time' => '3-7 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
            [
                'name' => 'Layanan Pengaduan dan Aspirasi',
                'service_category_id' => $categories['Kehumasan'],
                'description' => 'Layanan penyampaian pengaduan dan aspirasi masyarakat.',
                'requirements' => "- Identitas pengadu\n- Kronologi pengaduan\n- Bukti/dokumen pendukung\n- Usulan perbaikan",
                'workflow' => "1. Penyampaian pengaduan\n2. Verifikasi pengaduan\n3. Investigasi\n4. Tindak lanjut\n5. Pemberitahuan hasil",
                'processing_time' => '14-30 hari kerja',
                'cost' => 'Gratis',
                'contact' => '(0358) 321085',
                'office' => 'Kantor Kemenag Kabupaten Nganjuk',
                'is_active' => true,
            ],
        ];

        foreach ($services as $service) {
            Service::create($service);
        }
    }
}
