<?php

namespace App\Http\Controllers;

use App\Models\Setting;
use Illuminate\Http\Request;

class RegulasiController extends Controller
{
    /**
     * Display the regulasi (regulation) page.
     */
    public function index()
    {
        $settings = Setting::first();

        // Regulation data organized by category
        $regulasi = [
            'Undang-Undang' => [
                ['title' => 'Himpunan Peraturan Perundang-Undangan Tentang Penyiaran Digital', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/apou1450440290.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomer 33 Tahun 2014 Tentang Jaminan Produk Halal', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/kbur1421043064.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomer 34 Tahun 2014 Tentang Pengelolaan Haji', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/apjh1421040372.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomer 13 Tahun 2008 Tentang Penyelenggaraan Ibadah Haji', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/ywit1412141928.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomer 34 Tahun 2009 Tentang Penetapan Peraturan Pemerintah Pengganti UU Nomer 2 Tahun 2009 Tentang Perubahan Atas UU Nomer 13 Tahun 2008 Tentang Penyelenggaraan Ibadah Haji Menjadi UU', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/nhlx1412141910.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomer 5 Tahun 2014 Tentang Aparatur Sipil Negara (ASN)', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/zspa1397463645.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomer 9 Tahun 2010 Tentang Keprotokolan', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/gype1397464356.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomer 23 Tahun 2011 Tentang Pengelolaan Zakat', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/bosd1397464066.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 11 Tahun 2008 Tentang Informasi Dan Transaksi Elektronik', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/tskn1397872423.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 32 Tahun 2002 Tentang Penyiaran', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/saig1397872416.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 40 Tahun 1999 Tentang PERS', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/zaut1397872405.pdf'],
                ['title' => 'Undang-Undang Republik Indonesaia Nomor 36 Tahun 1999 Tentang Telekomunikasi', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/aiyv1397872386.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 14 Tahun 2008 Tentang Keterbukaan Informasi Publik', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/fgim1397872368.pdf'],
                ['title' => 'Penetapan Presiden Republik Indonesia Nomor 1/PNPS Tahun 1965 Tentang Pencegahan Penyalahgunaan Dan/Atau Penodaan Agama', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/owiz1398054257.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 1 Tahun 1974 Tentang Perkawinan', 'url' => 'http://jatim.kemenag.go.id/backend/artikel/24320/%20http:/jatim.kemenag.go.id/file/file/Undangundang/kyfs1398054248.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 17 Tahun 2003 Tentang Keuangan Negara', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/cabg1398054241.pdf'],
                ['title' => 'Undang-Undang 1946 Nomor 22 Tentang Pencatatan Nikah, Nikah, Talak Dan Rujuk', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/dgzy1398054233.pdf'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 44 Tahun 2008 Tentang Pornografi', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/rfni1398054224.pdf'],
                ['title' => 'Undang-Undang Nomor 6 Tahun 2006 Tentang Pengesahan International Convention For The Suppression Of The Financing Of Terrorism, 1999', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/nial1450431287.pdf'],
                ['title' => 'Undang-Undang Nomor 5 Tahun 2006 Tentang Pengesahan International Convention For The Suppression Of Terrorist Bombings, 1997', 'url' => 'http://jatim.kemenag.go.id/backend/artikel/24320/(KONVENSI%20INTERNASIONAL%20PEMBERANTASAN%20PENGEBOMAN%20OLEH%20TERORIS,%201997)%20'],
                ['title' => 'Undang-Undang Republik Indonesia Nomor 15 Tahun 2003 Tentang Penetapan Peraturan Pemerintah Pengganti Undang-Undang Nomor 1 Tahun 2002 Tentang Pemberantasan Tindak Pidana Terorisme Menjadi Undang-Undang', 'url' => 'http://jatim.kemenag.go.id/file/file/Undangundang/izpd1450430713.pdf'],
                ['title' => 'Undang-Undang (UU) Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik', 'url' => 'https://ppid.kemenag.go.id/v3/downlot.php?file=60UU_No_14_Tahun_2008_tentang_KIP.pdf'],
            ],
            'Peraturan Pemerintah' => [
                ['title' => 'PERATURAN PEMERINTAH NOMOR 11 TAHUN 2017 MANAJEMEN PEGAWAI NEGERI SIPIL', 'url' => 'http://jatim.kemenag.go.id/files/jatim/file/file/PP/PP_Nomor_11_Tahun_2017_(PP_Nomor_11_Tahun_2017).pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 70 TAHUN 2015 TENTANG JAMINAN KECELAKAAN KERJA DAN JAMINAN KEMATIAN BAGI PEGAWAI ASN', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/lyso1450343239.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 48 TAHUN 2014 TENTANG PERUBAHAN ATAS PERATURAN PEMERINTAH NOMOR 47 TAHUN 2004 TENTANG TARIF ATAS JENIS PENERIMAAN NEGARA BUKAN PAJAK YANG BERLAKU PADA DEPARTEMEN AGAMA', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/jyuw1405563051.PDF'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 22 TAHUN 2013 TENTANG PERATURAN GAJI PEGAWAI NEGERI SIPIL', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/jmpt1400478832.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 71 TAHUN 2010 TENTANG STANDAR AKUNTANSI PEMERINTAHAN', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/kazs1397462246.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 28 TAHUN 2012 TENTANG PELAKSANAAN UNDANG-UNDANG NOMOR 43 TAHUN 2009 TENTANG KEARSIPAN', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/nehu1397462196.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 79 TAHUN 2012 TENTANG PELAKSANAAN UNDANG UNDANG NOMOR 13 TAHUN 2008 TENTANG PENYELENGGARAAN IBADAH HAJI', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/dwtg1397462227.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 82 TAHUN 2012 TENTANG PENYELENGGARAAN SISTEM DAN TRANSAKSI ELEKTRONIK', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/pavg1397462240.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 96 TAHUN 2012 TENTANG PELAKSANAAN UNDANG-UNDANG NOMOR 25 TAHUN 2009 TENTANG PELAYANAN PUBLIK', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/lnpo1397462220.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 53 TAHUN 2010 TENTANG DISIPLIN PEGAWAI NEGERI SIPIL', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/ftld1397462170.pdf'],
                ['title' => 'PERATURAN PEMERINTAH REPUBLIK INDONESIA NOMOR 61 TAHUN 2010 TENTANG PELAKSANAAN UNDANG-UNDANG NOMOR 14 TAHUN 2008 TENTANG KETERBUKAAN INFORMASI PUBLIK', 'url' => 'http://jatim.kemenag.go.id/file/file/PP/bsjg1397462210.pdf'],
            ],
            'Peraturan Presiden' => [
                ['title' => 'Perpres No 152 Tahun 2024 tentang Kementerian Agama', 'url' => 'https://cdn.kemenag.go.id/storage/archives/salinan-perpres-nomor-152-tahun-2024-tentang-kementerian-agamapdf.pdf'],
            ],
            'PMA' => [
                ['title' => 'PMA nomor 47 Tahun 2017 tentang pengelolaan dana haji', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA%2047%202017/PMA%20nomor%2047%20Tahun%202017%20tentang%20pengelolaan%20dana%20haji.pdf'],
                ['title' => 'PMA nomor 58 Tahun 2017 tentang kepala madrasah', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA%2058%202017/PMA%20nomor%2058%20Tahun%202017%20tentang%20kepala%20madrasah.pdf'],
                ['title' => 'PMA nomor 35 Tahun 2016 tentang lembaga pembinaan dan pengembangan pesta paduan suara gerejani Katolik', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA%2035%202016/PMA%20No%2035%20Tahun%202016%20tentang%20lembaga%20pembinaan%20dan%20pengembangan%20pesta%20paduan%20suara%20gerejani%20Katolik.pdf'],
                ['title' => 'PMA Nomer 12 Tahun 2016 Ttg Pengelolaan penerimaan negara bukan pajak atas biaya nikah atau rujuk di luar kantor urusan agama', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/fxnl1460107098.pdf'],
                ['title' => 'PMA Nomer 29 Tahun 2015 Ttg Perubahan Atas PMA Nomor 14 Tahun 2012 Ttg Penyelenggaraan Haji Reguler', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/vhlf1455071127.pdf'],
                ['title' => 'PMA Nomer 68 Tahun 2015 Ttg Pengangkatan Dan Pemberhentian Rektor Dan Ketua Pada Perguruan Tinggi Keagamaan Yang Diselenggarakan Oleh Pemerintah', 'url' => 'https://jatim.kemenag.go.id/file/file/pdf/ncvr1449538773.pdf'],
                ['title' => 'PMA Nomer 67 Tahun 2015 Ttg Bantuan Pemerintah Pada Kementerian Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/rucl1447902573.pdf'],
                ['title' => 'PMA Nomer 44 Tahun 2014 Ttg Organisasi Dan Tata Kerja Unit Pelaksana Teknis Asrama Haji', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/dmwr1417765516.pdf'],
                ['title' => 'PMA Nomer 43 Tahun 2014 Ttg Tata Cara Pembayaran Tunjangan Profesi Guru Bukan Pegawai Negeri Sipil (PNS) Pada Kementerian Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/dryv1417751005.pdf'],
                ['title' => 'PMA Nomer 90 Tahun 2013 Ttg Penyelenggaraan Pendidikan Madrasah', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/yfvp1413867490.pdf'],
                ['title' => 'PMA Nomer 13 Tahun 2014 Ttg Pendidikan Keagamaan Islam', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/ihdp1412150669.PDF'],
                ['title' => 'PMA Nomer 14 Tahun 2014 Ttg Pendirian Madrasah Yang Diselenggarakan Oleh Pemerintah Dan Penegerian Madrasah Yang Diselenggarakan Oleh Masyarakat', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/ncjx1412150264.PDF'],
                ['title' => 'PMA Nomer 29 Tahun 2014 Ttg Kepala Madrasah', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/drin1412150101.PDF'],
                ['title' => 'PMA No. 6 Tahun 2014 Ttg Penyediaan Konsumsi Jemaah Haji Indonesia Di Arab Saudi', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/bfdc1412142276.pdf'],
                ['title' => 'PMA No. 3 Tahun 2014 Ttg Penyediaan Akomodasi Jemaah Haji Indonesia Di Arab Saudi', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/maif1412142328.pdf'],
                ['title' => 'PMA No. 10 Tahun 2010 Ttg Organisasi Dan Tata Kerja Kementerian Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/mqho1398054567.pdf'],
                ['title' => 'PMA No. 75 Tahun 2013 Ttg Layanan Pengadaan Barang & Jasa', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/rpun1395809334.pdf'],
                ['title' => 'PMA No. 4 Tahun 2013 Ttg Pengelolaan Dana Abadi Umat', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/nvoj1395809231.pdf'],
                ['title' => 'PMA No. 34 Tahun 2013 Ttg Pengisian Sisa Kuota Haji Nasional', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/cxfh1395809151.pdf'],
                ['title' => 'PMA No. 30 Tahun 2013 Ttg Bank Penerima Setoran', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/sdty1395809111.pdf'],
                ['title' => 'PMA No. 3 Tahun 2013 Ttg Organisasi & Tata Kerja Asrama Haji', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/mufg1395757144.pdf'],
                ['title' => 'PMA No. 14 Tahun 2012 Ttg Penyelenggaraan Ibadah Haji Reguler', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/ithw1395757016.pdf'],
                ['title' => 'PMA No. 28 Tahun 2013 Ttg Disiplin Kehadiran PNS', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/mfev1395756929.pdf'],
                ['title' => 'PMA No. 22 Tahun 2011 Ttg Standar Pelayanan Minimal Pelayanan Haji Khusus', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/yexv1395756743.pdf'],
                ['title' => 'PMA No. 13 Tahun 2012 Ttg Organisasi & Tata Kerja Instansi Vertikal Kemenag', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/tlie1395756371.pdf'],
                ['title' => 'PMA No. 6 Tahun 2010 Ttg Prosedur & Persyaratan Pendaftaran Haji', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/lmnp1395753752.pdf'],
                ['title' => 'PMA no. 5 Tahun 2010 Ttg Penetapan PHBI Tk. Kenegaraan', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/wkmp1395753672.pdf'],
                ['title' => 'PMA No. 10 Tahun 2010 Ttg Organisasi Tata Kerja', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/gsyn1395753514.pdf'],
                ['title' => 'MA No. 1 Tahun 2010 Ttg Perubahan Penyebutan Departemen Agama Menjadi Kementerian Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/rlta1395737073.pdf'],
                ['title' => 'PMA No. 4 Tahun 2009 Ttg Administrasi Pendaftaraan Wakaf Uang', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/oejh1395737030.pdf'],
                ['title' => 'PMA No. 3 Tahun 2006 Ttg Organisasi & Tata Kerja Departemen Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/hbzi1395717650.pdf'],
                ['title' => 'PMA No. 8 Tahun 2006 Ttg Visi Misi Departemen Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/xdqb1395717681.pdf'],
                ['title' => 'PMA No. 21 Tahun 2006 Ttg Petunjuk Penyusunan Akuntabilitas Kinerja', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/alzc1395717722.pdf'],
                ['title' => 'PMA No. 11 Tahun 2007 Ttg Pencatatan Nikah', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/viwe1395722379.pdf'],
                ['title' => 'PMA No. 8 Tahun 2007 Ttg Pengawasan Di Lingkungan Depag', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/hvyu1395722794.pdf'],
                ['title' => 'PMA No. 9 Tahun 2007 Ttg Baperjakat', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/gpns1395722810.pdf'],
                ['title' => 'PMA No. 1 Tahun 2008 Ttg Perubahan PMA No. 15 Tahun 2006', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/ehpw1395722833.pdf'],
                ['title' => 'PMA No. 19 Tahun 2009 Ttg Pembentukan KUA Jatim', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/mnpg1395722846.pdf'],
                ['title' => 'PMA No. 2 Tahun 2008 Ttg Standar Kompetensi Lulusan Dan Isi PAI & Bahasa Arab Di Madrasah', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/zpwn1395722871.pdf'],
                ['title' => 'PMA No. 15 Tahun 2006 Ttg Pendaftaran Haji', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/ryha1395716272.pdf'],
                ['title' => 'PMA No. 30 Tahun 2005 Ttg Wali Hakim', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/wjzo1395715918.pdf'],
                ['title' => 'PMA No. 21 Tahun 2005 Ttg Pengelolaan Biaya Nikah Rujuk', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/yvxa1395715719.pdf'],
                ['title' => 'PMA No. 31 Tahun 2005 Ttg Pemberian Kuasa & Pendelegasian Wewenang Penandatanganan SK Inpassing JF. Penghulu', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/zhck1395716257.pdf'],
                ['title' => 'PMA Nomor 63 Tahun 2016 Tentang Perubahan Atas PMA Nomor 45 Tahun 2014 Tentang Pejabat Perbendaharaan Negara Pada Kementerian Agama', 'url' => 'https://drive.google.com/file/d/1rBq01Tq2tt-mMbJUEKb8Q8tU6ut1C_D7/view?usp=sharing'],
                ['title' => 'PMA Nomor 62 Tahun 2016 Tentang Perubahan Kedua Atas PMA Nomor 67 Tahun 2015 Tentang Bantuan Pemerintah Pada Kementerian Agama', 'url' => 'https://drive.google.com/file/d/10A6Wmee_Ksn7HQG29Yy592e2UcGskNeS/view?usp=sharing'],
                ['title' => 'PMA No. 4 Tahun 2014 Ttg Penyediaan Transportasi Darat Jemaah Haji Indonesia Di Arab Saudi', 'url' => 'https://jatim.kemenag.go.id/file/file/PMA/maif1412142328.pdf'],
                ['title' => 'PMA No. 16 Tahun 2010 Pengelolaan Pendidikan Agama Pada Sekolah', 'url' => 'https://jatim.kemenag.go.id/file/file/peraturantentangPNS/gtrq1413864104.pdf'],
            ],
            'KMA' => [
                ['title' => 'Keputusan Ketua Mahkamah Agung (KMA) Nomor 085 Tahun 2011 tentang Pembentukan Kelompok Kerja Penyusunan Peraturan Mahkamah Agung tentang Tata Cara Penyelesaian Gugatan Atas Putusan Komisi Informasi Pada Pengadilan Tata Usaha Negara dan/atau Pengadilan Negeri', 'url' => 'https://ppid.kemenag.go.id/v3/downlot.php?file=77surat-keputusan-ketua-ma-ri-085-2011-penyelesaian-gugatan-putusan-kip-ptun.pdf'],
                ['title' => 'Keputusan Menteri Agama (KMA) Nomor 533 Tahun 2018 tentang Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama', 'url' => 'https://ppid.kemenag.go.id/v3/downlot.php?file=81KMA-533-Tahun-2018-ttg-PPID-Kementerian-Agama-dan-Atasan-PPID-Kementerian-Agama.pdf'],
                ['title' => 'Keputusan Menteri Agama (KMA) Nomor 92 Tahun 2019 tentang Pedoman Layanan Informasi Publik Bagi Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama dan Atasan Pejabat Pengelola Informasi dan Dokumentasi Kementerian Agama', 'url' => 'https://produk-hukum.kemenag.go.id/dokumen/1550'],
                ['title' => 'KMA No. 208 Tahun 2017 Tentang Pedoman Penyesuaian/Inpassing, Uji Kompetensi dan Penetapan Kebutuhan Jabatan Fungsional Penghulu', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA%20Inpasing%20KUA/KMA%20Inpasing%20Kepala%20KUA%20Kecamatan%20Nomor%20208%202017.pdf'],
                ['title' => 'KMA No. 777 Tahun 2016 tentang Pedoman Penyusunan Keputusan dan Instrumen Hukum Lainnya pada Kementerian Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/1_KMA_PEDOMAN_PER-UU/1_KMA_PEDOMAN_PER-UU.pdf'],
                ['title' => 'KMA No. 9 Tahun 2016 Tentang Pedoman Tata Naskah Dinas', 'url' => 'https://jatim.kemenag.go.id/file/file/kma%20persuratan%20No.%209/kma%20persuratan.pdf'],
                ['title' => 'KMA No. 419 Tahun 2016 Tentang Pembentukan Panic Pelaksana Hari Amal Bakti Kementerian Agama Ke-70 Tahun 2016', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/tsmx1452071576.pdf'],
                ['title' => 'KMA No. 39 Tahun 2015 Tentang Rencana Strategis Kementerian Agama Tahun 2015', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/fhjo1455069672.rar'],
                ['title' => 'KMA No. 17 Tahun 2015 Tentang Penetapan Embarkasi dan Debarkasi Haji Tahun 1436 H/2015 M', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/dtow1425354112.pdf'],
                ['title' => 'KMA No. 189 Tahun 2014 Tentang Penetapan Provinsi Nusa Tenggara Barat Sebagai Tempat Penyelenggaraan Musabaqoh Tilawatil Quran Nasional XXVI Tahun 2016', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/qmzx1452134650.pdf'],
                ['title' => 'KMA No. 64 Tahun 2014 Tentang Penetapan Kuota Haji Tahun 1435 H/2014 M', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/fxcp1412142669.pdf'],
                ['title' => 'KMA No. 68 Tahun 2014 Tentang Penetapan Bandara Embarkasi Tahun 1435 H/2014 M', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/erld1412142719.pdf'],
                ['title' => 'KMA No. 52 Tahun 2014 Tentang Penetapan Embarkasi dan Debarkasi Haji Tahun 1435 H/2014 M', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/pusf1412142753.pdf'],
                ['title' => 'KMA No. 158 Tahun 2014 Tentang Penetapan Tanggal 1 Zulhijah 1435 H', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/kdcl1412139748.pdf'],
                ['title' => 'KMA No. 118 Tahun 2014 Tentang Pembentukan Badan Amil Zakat Nasional Provinsi', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/zknm1412139807.pdf'],
                ['title' => 'KMA No. 117 Tahun 2014 Tentang Implementasi Kurikulum 2013 Di Madrasah', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/estc1407115304.pdf'],
                ['title' => 'KMA No. 98 Tahun 2014 Tentang Penetapan Akun Media Sosial Kemenag', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/kwym1404265309.pdf'],
                ['title' => 'KMA No. 99 Tahun 2014 Tentang Penetapan 1 Ramadhan 2014', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/fbdn1404265366.pdf'],
                ['title' => 'KMA No. 20 Tahun 2014 Tentang Penunjukan Kuasa Pengguna Anggaran', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/wmbn1395843881.pdf'],
                ['title' => 'KMA No. 91 Tahun 2013 Tentang Pejabat Yang Wajib Menyampaikan Laporan Harta Kekayaan Penyelenggara Negara', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/lodq1395821792.pdf'],
                ['title' => 'KMA No. 13 Tahun 2010 Tentang Organisasi dan Tata Kerja Instansi Vertikal Kementerian Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/ckgn1426053054.pdf'],
                ['title' => 'KMA No. 44 Tahun 2010 Tentang Pedoman Penataan Kearsipan Di Lingkungan Kementerian Agama', 'url' => 'https://jatim.kemenag.go.id/file/file/KMA/nlzd1404983175.pdf'],
            ],
            'Surat Edaran' => [
                ['title' => 'Surat edaran nomor B-1515/SJ/B.II.4/Kp.07.6/02/2018 tentang pelaksanaan penyesuaian/inpassing pegawai negeri sipil Kementerian Agama RI dalam jabatan fungsional pengelola pengadaan barang/jasa', 'url' => 'http://jatim.kemenag.go.id/file/file/SE%20tentang%20pelaksanaan%20inpassing%20PNS%20kemenag%20(22022019)/SE%20tentang%20pelaksanaan%20inpassing%20PNS%20kemenag%20(22022019).pdf'],
                ['title' => 'Surat Menteri PANRB tentang Pelaksanaan Netralitas bagi ASN pada Penyelenggaraan Pilkada Serentak Tahun 2018, Pemilihan Legislatif Tahun 2019, dan Pemilihan Presiden dan Wakil Presiden Tahun 2019', 'url' => 'http://jatim.kemenag.go.id/file/file/Surat%20edaran%20netralitas%20ASN%20di%20Pilkada/20171227_Surat_Menteri_Netralitas.pdf'],
                ['title' => 'Surat Edaran Tentang Himbauan tidak memberikan cuti tahunan PNS di lingkungan Kementerian Agama sebelum dan sesudah cuti bersama Elías Fitri 1 Syawal 1438 H', 'url' => 'http://jatim.kemenag.go.id/file/file/SE%20Himbauan%20tidak%20memberikan%20cuti%20tahunan%20PNS%202017/SE%20tentang%20Himbauan%20Tidak%20Memberikan%20Cuti%20Tahunan%20PNS%20tahun%202017.pdf'],
                ['title' => 'Surat Edaran Mendagri nomer 905/117/SJ tentang pendanaan forum kerukunan umat beragama dalam anggaran pendapatan belanja daerah', 'url' => 'http://jatim.kemenag.go.id/file/file/SE%20Mendagri/Surat_Edaran_Menteri_Dalam_Negeri.docx'],
                ['title' => 'Surat edaran Direktur Jenderal Bimas Islam nomer B-2674/DJ.III/KW.00/9/2017 tentang pencatatan perjanjian perkawinan', 'url' => 'http://jatim.kemenag.go.id/file/file/SE%20pencatatan%20perjanjian%20perkawinan/SE-Pencatatan-Perjanjian-Perkawinan.pdf'],
                ['title' => 'SE Sekjen Nomer 1558 Tahun 2017 Tentang Kebijakan Penggunaan Internet dan Intranet di Lingkungan Kementerian Agama', 'url' => 'http://jatim.kemenag.go.id/files/jatim/file/file/informasipenting/SE_tentang_kebijakan_jaringan_internet_dan_intranet.pdf'],
                ['title' => 'SE Sekjen Nomer 1767 Tahun 2016 Tentang Penilaian dan Penetapan Angka Kredit Jabatan Fungsional Pengelola Pengadaan Barang/Jasa Kementerian Agama', 'url' => 'http://jatim.kemenag.go.id/file/file/SuratEdaranSekjen/mgyx1457753581.pdf'],
                ['title' => 'SE Sekjen Nomer 1306 Tahun 2015 Tentang Pelaksanaan Penyusunan Bahan Publikasi Tingkat Provinsi', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/ivmd1450344229.pdf'],
                ['title' => 'SE Sekjen Nomer 8756 Tahun 2015 Tentang Pengumuman Rencana Umum Pengadaan (RUP) Kementerian Agama Tahun Anggaran 2016', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/nkej1450323863.pdf'],
                ['title' => 'SE Sekjen Nomer 7596 Tahun 2015 Tentang Pelaksanaan Pengadaan Barang/Jasa Melalui Penunjukan Langsung Dan E-Purchasing Di Lingkungan Kementerian Agama', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/itsq1447902954.pdf'],
                ['title' => 'SE Sekjen Nomer 4999 Tahun 2015 Tentang Langkah-langkah Strategis Penyerapan Anggaran Triwulan III', 'url' => 'http://jatim.kemenag.go.id/file/file/SuratEdaranSekjen/xiph1438770796.pdf'],
                ['title' => 'SE Sekjen Nomer 05803 Tahun 2015 Tentang Penerbitan Dan Perubahan SK Jabatan Fungsional Umum Pada Kementerian Agama', 'url' => 'http://jatim.kemenag.go.id/file/file/SuratEdaranSekjen/igkp1438770806.pdf'],
                ['title' => 'Keputusan Sekjen Nomer 5 Tahun 2015 Tentang Petunjuk Teknis Tata Kelola Kegiatan Pertemuan/Rapat Di Luar Kantor', 'url' => 'http://jatim.kemenag.go.id/file/file/SuratEdaranSekjen/flcy1438770835.pdf'],
                ['title' => 'SE Sekjen Tentang Implementasi Pelaksanaan Sistem Pendataan Ulang PNS Elektronik', 'url' => 'http://jatim.kemenag.go.id/file/file/SuratEdaranSekjen/hbgf1438770790.zip'],
                ['title' => 'SE Sekjen Nomer 4614 Tahun 2015 Tentang Petunjuk Tehnis Pelaksanaan Pemberian Gaji/Tunjangan Bulan Ketiga Belas Pada Kementerian Agama', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/xcqp1436323646.pdf'],
                ['title' => 'SE Sekjen Nomer 06132 Tahun 2015 Tentang Pelaksanaan Cuti Bersama PNS Pada Kemenag Sebelum Dan Sesudah Hari Raya Elías Fitri 1 Syawal 1436 H', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/fjkx1436323653.pdf'],
                ['title' => 'SE Sekjen Nomer 2889 Tahun 2015 Tentang Penggunaan Produk Dalam Negeri Bagi Aparatur Sipil Negara', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/rbwl1436849491.pdf'],
                ['title' => 'SE Sekjen Nomer 92 Tahun 2015 Tentang Pencegahan Dan Pemberantasan Penyalahgunaan Dan Peredaran Gelap Narkotika Dan Prekursor Narkotika Melalui Kegiatan Keagamaan', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/dkza1436850402.pdf'],
                ['title' => 'Surat Edaran Bersama Sekretaris Jenderal Departemen Agama, Jaksa Agung Muda Intelijen, Dan Direktus Jenderal Kesatuan Bangsa Dan Politik Departemen Dalam Negeri', 'url' => 'http://jatim.kemenag.go.id/file/file/pdf/edzh1450431972.pdf'],
                ['title' => 'Tuntunan Penggunaan Pengeras Suara di Masjid & Mushala', 'url' => 'http://jatim.kemenag.go.id/file/file/Tuntunan%20penggunaan%20pengeras%20suara%20musholla%20dan%20masjid/Tuntunan%20Pengeras%20Suara%20di%20Masjid%20dan%20Mushala%20(1978).pdf'],
            ],
        ];

        return view('regulasi', [
            'settings' => $settings,
            'regulasi' => $regulasi,
            'meta_title' => 'Regulasi - ' . ($settings->site_name ?? 'Kementerian Agama Kabupaten Nganjuk'),
        ]);
    }
}
